import { Roboto } from "next/font/google";
import App from "./_components/App";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Head from "next/head";

const inter = Roboto({ subsets: ["latin"], weight: "700" });

export const metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Head>
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <body className={`${inter.className}`}>
          <App children={children} />
        </body>
      </html>
    </ClerkProvider>
  );
}
